config: lower-case first word of error strings
This follows our usual style (both throughout git, and
throughout the rest of this file).

This covers the whole file, but note that I left the capitalization in
the multi-sentence:

  error: malformed value...
  error: Must be one of ...

because it helps make it clear that we are starting a new sentence in
the second one.

Signed-off-by: Jeff King <peff@peff.net>
Signed-off-by: Junio C Hamano <gitster@pobox.com>

cregit: 8c3ca351cb125c94870d7b8278a7efa1f1474d22 http://github.com/git/git/commit/8c3ca351cb125c94870d7b8278a7efa1f1474d22